name: Publish Project

on:
  workflow_dispatch:
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - main

# Doesn't work setting as a variable for some reason, so the value is hard-coded throughout 😢.
# May be fixed by Github down the road?
# env:
#   workflow_repo: wsuwebteam/wsuwp-workflows

jobs:
  build-project:
    name: Build Project
    # if: github.event.pull_request.merged == true
    uses: wsuwebteam/wsuwp-workflows/.github/workflows/build-project.yml@main
    with:
      node_version: 14

  release-project:
    name: Release Project
    uses: wsuwebteam/wsuwp-workflows/.github/workflows/release-project.yml@main
    needs: build-project
    with:
      artifact_name: ${{ needs.build-project.outputs.artifact_name }}
      workflow_repo: wsuwebteam/wsuwp-workflows

  deploy-project:
    name: Deploy Project
    uses: wsuwebteam/wsuwp-workflows/.github/workflows/deploy-project.yml@main
    needs: release-project
    with:
      release_id: ${{ needs.release-project.outputs.release_id }}
      release_asset: ${{ needs.release-project.outputs.release_asset }}
      workflow_repo: wsuwebteam/wsuwp-workflows
    secrets:
      PAT: ${{ secrets.PAT }}
