name: "Test Delete AWS"

on:
  delete:
    branches-ignore:
      - "protect"
      - "main"

env:
  BRANCH: ${{ github.event.ref }}

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Github context
        run: echo "${{ toJson(github) }}"

      # - name: Set Branch name
      #   run: |
      #     BRANCH=$(cat ${{ github.event_path }} | jq --raw-output '.ref')
      #     echo "${{ github.repository }} has ${BRANCH} branch"
      #     echo "::set-env name=STAGE::$(echo ${BRANCH})"

      - name: Echo Branch name
        run: echo Deleting from S3 ${{ env.REPO_NAME }}

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-west-2
      - name: Delete folder from S3
        run: |
          echo "Delete folder from S3 - ${{ env.REPO_NAME }}"
        # aws s3 rm s3://cdn-web-wsu/designsystem/dans-test/${{ github.ref_name }}/
