name: "Test Delete AWS"

on:
  delete:
    branches-ignore:
      - "main"

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Delete folder from S3
        run: echo "Delete folder from S3 - ${{ github.ref_name }}"
        # run: aws s3 rm s3://cdn-web-wsu/dans-test/${{ github.ref_name }}/
