name: "Test Delete AWS"

on:
  delete:

jobs:
  default:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.event.ref }}
    steps:
      - name: Github context
        run: |
          echo "${{ toJson(github) }}"

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-west-2
      - name: Delete folder from S3
        run: |
          echo "Delete folder from S3 - ${{ env.BRANCH }}"
          echo "Delete folder from S3 - s3://cdn-web-wsu/designsystem/dans-test/${{ env.BRANCH }}/"
        # aws s3 rm s3://cdn-web-wsu/designsystem/dans-test/${{ github.ref_name }}/
